# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2026 Steve Clarke <stephenlclarke@mac.com> - https://xyzzy.tools

sonar.projectKey=stephenlclarke_mytimebuddy
sonar.organization=stephenlclarke
sonar.host.url=https://sonarcloud.io
sonar.projectName=mytimebuddy
sonar.projectVersion=0.1.0

sonar.sources=MyTimeBuddy
sonar.tests=MyTimeBuddyTests
sonar.sourceEncoding=UTF-8

sonar.exclusions=build/**,**/*.xcodeproj/**,**/xcuserdata/**,**/*.xcresult/**,.scannerwork/**
sonar.coverage.exclusions=MyTimeBuddyTests/**
sonar.qualitygate.wait=true
